theme: jekyll-theme-cayman
layout: default
markdown: kramdown
kramdown:
  toc_levels: 1..2
title: "FastFit: Towards Real-Time Iterative Neural Vocoder for Text-to-Speech
by Replacing U-Net Encoder with Multiple STFTs"
description: Anonymous submission to INTERSPEECH 2023
